### ISSUE TITLE
How long does the training stage take?

### ISSUE THREAD

**Issue by berry-ding** [seanhe97/MKT#11]
Hi, I think this is a great job. I want to know how long does the training stage take and which kind of GPUs you use?

**Comment by sunanhe** [comment]
Hi, sorry for late response.

For nus-wide dataset:
On 1xV100, the first training stage takes about 6 hours for 20 epoch.
On 8xV100, the second training stage takes about 1 hours for 4 epoch.

Best,
Sunan
