### ISSUE TITLE
negative samples in ranking loss?

### ISSUE THREAD

**Issue by bnu-wangxun** [seanhe97/MKT#2]
Your paper is really a good work about Open-Vocabulary Multi-Label Classification. But I have two questions:
--- How do you choose negative samples in your ranking loss? 
--- The paper states that "Motivated by CoOp (Zhou et al. 2021), we introduce prompt tuning for the adaptation of label embedding. During the tuning process, all parameters except for context embedding of prompt template illustrated as the dotted box named prompt template in Figure 2, are fixed. " what does parameters of context embedding of prompt template mean?

**Comment by sunanhe** [comment]
Sorry for the late reply. 
1. Negative samples are nagetive label embeddings in an image.
2. Context Embeddings are the token embeddings of the words in template.

Best regards.
