### ISSUE TITLE
nus_wide_test.h5，nus_wide_train.h5 unavailable

### ISSUE THREAD

**Issue by SeuZL** [seanhe97/MKT#3]
你好，我在尝试复现您的实验，但是不知道您论文中数据集的组织结构是如何构建的。
您给出的数据集地址中下载的数据集并不是按您的架构组织的，所以您给出架构中的feature和Flicker文件夹中应该是放入哪些文件？
还有就是nus_wide_test.h5，nus_wide_train.h5两个文件是从哪下载的，我在您给出的NUS_WIDE官网中并没有找出这两个文件的下载地址，能麻烦指导下吗。
本人水平有限，如果问了很笨比的问题，请多多包涵

**Comment by sunanhe** [comment]
You can download these files following the instruction in preparation.

> 3. Download annotations following the [BiAM](https://github.com/akshitac8/BiAM) from [here](https://drive.google.com/drive/folders/1jvJ0FnO_bs3HJeYrEJu7IcuilgBipasA?usp=sharing).

**Comment by ankitpandey0392** [comment]
Sir, authors of BIAM have deleted the file from their drive. can anyone please upload it and share link?
