### ISSUE TITLE
 TP = (labels[mask] == 1).sum().float() RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by sorrowyn** [seanhe97/MKT#4]
![图片](https://user-images.githubusercontent.com/19569162/221356946-5c7d3682-4d33-480d-9d2b-17b2c62a31a2.png)

**Comment by sunanhe** [comment]
Hi, thanks for your attention and problem.

I think this is because of the mismatch between ```labels``` and ```mask```. Maybe you can check the shape of them.

Best,
Sunan.
