### ISSUE TITLE
NUS-Wide Images

### ISSUE THREAD

**Issue by Priptide** [seanhe97/MKT#5]
This paper is great I am just wondering about the implementation when using the NUS-Wide dataset is it intended that you should download all the images from the NUS-Wide image list as there is no provided file for all the images?

If so which image sizes did this model use as they provide three different sizes for each image?

**Comment by sunanhe** [comment]
Hi, 

Thanks for your attention and problem. Yes, you have to apply for the origin image files of NUS-WIDE through the link we provide. We don't have the copyright of this dataset so we cannot share the images with you.

I will close the issue. If you still have any problems, plz tell me.

Best,
Sunan.
