### ISSUE TITLE
Question about model, clip model

### ISSUE THREAD

**Issue by SeonghaEom** [seanhe97/MKT#7]
Hi, I am currently reproducing your paper, and I have a question.
According to your paper, backbone is ViT and VLP is clip.
But the first stage code loads model and VLP from same argument (arg.clip_path, https://github.com/sunanhe/MKT/blob/main/train_nus_first_stage.py)
Are they same or different?

**Comment by sunanhe** [comment]
Hi,

Thanks for your attention and problem. The vision encoder of clip model is almost same with ViT. We found that the CLIP version achieved better performance. You can refer to the supplementary of the updated version paper.

I will close the issue. If you still have any problems, plz tell me.

Best,
Sunan.
